framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: redis.cache.default
        default_redis_provider: app.redis_provider

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            cache.product:
                adapter: redis.cache.product
                provider: app.redis_provider

            cache.category:
                adapter: redis.cache.category
                provider: app.redis_provider

            cache.customer_photos:
                adapter: redis.cache.customer_photos
                provider: app.redis_provider

            cache.product_type:
                adapter: redis.cache.product_type
                provider: app.redis_provider

            cache.store:
                adapter: redis.cache.store
                provider: app.redis_provider
